# Monitor Rules
env=DISPLAY,:2
monitorrule=name:eDP-1,width:2560,height:1440,refresh:165,x:0,y:0,scale:1.5,vrr:2,rr:0
monitorrule=name:DP-2,width:1920,height:1080,refresh:165,x:0,y:0,scale:1,vrr:2,rr:0


