# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x1a110cff
bordercolor = 0xa48c7fff
dropcolor = 0xffb68b80
splitcolor = 0xc5cf46ff
focuscolor = 0xffb68bff
maximizescreencolor = 0xf9b993ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xc5cf46ff
globalcolor = 0xe67c31ff
overlaycolor = 0x683c1fff
jump_label_decorate_fg_color = 0xf2dfd5ff
jump_label_decorate_bg_color = 0x322822ff
jump_label_decorate_focus_fg_color = 0x522300ff
jump_label_decorate_focus_bg_color = 0xffb68bff
jump_label_decorate_border_color = 0xa48c7fff
group_bar_decorate_fg_color = 0xf2dfd5ff
group_bar_decorate_bg_color = 0x322822ff
group_bar_decorate_focus_fg_color = 0x522300ff
group_bar_decorate_focus_bg_color = 0xffb68bff
group_bar_decorate_border_color = 0xa48c7fff
