#!/usr/bin/env bash
# ~/.config/mango/theme-pick.sh
# Apply a FIXED theme from ~/.config/themes/<name>/colors.toml (Omarchy format).
# Unlike theme-switch.sh (wallpaper -> matugen), this uses hand-picked palettes
# for guaranteed legibility. Writes the same per-app color files matugen does,
# so last-write-wins between the two switchers (expected).
#
# Usage:
#   theme-pick.sh                 # rofi-pick a theme (shows preview.png thumbs)
#   theme-pick.sh tokyo-night     # apply a named theme directly
#
# Keeps the current wallpaper untouched.
set -euo pipefail

THEMES_DIR="$HOME/.config/themes"
STATE="$HOME/.cache/current-theme"

# ---- pick a theme -------------------------------------------------------
pick_theme() {
  # Only dirs that actually contain colors.toml count as themes (skips stray
  # folders like 'backgrounds'). Show preview.png as the icon when present.
  # rofi supports thumbnail:// previews.
  for d in "$THEMES_DIR"/*/; do
    [ -f "$d/colors.toml" ] || continue
    name=$(basename "$d")
    preview="$d/preview.png"
    if [ -f "$preview" ]; then
      printf '%s\0icon\x1f%s\n' "$name" "$preview"
    else
      printf '%s\n' "$name"
    fi
  done | rofi -dmenu -show-icons -p "wallpaper" -theme ~/.config/rofi/picker.rasi
}

case "${1:-}" in
"") THEME="$(pick_theme)" ;;
*) THEME="$1" ;;
esac
[ -z "${THEME:-}" ] && exit 0

TOML="$THEMES_DIR/$THEME/colors.toml"
[ -f "$TOML" ] || {
  echo "no colors.toml for theme: $THEME" >&2
  exit 1
}

# ---- parse colors.toml --------------------------------------------------
# Flat 'key = "#hex"' file. Pull a value by key. Strips quotes + leading '#'.
get() {
  sed -n "s/^$1[[:space:]]*=[[:space:]]*\"\?#\?\([0-9A-Fa-f]\{6\}\)\"\?.*/\1/p" "$TOML" | head -1
}

bg=$(get background)
fg=$(get foreground)
accent=$(get accent)
cur=$(get cursor)
selbg=$(get selection_background)
selfg=$(get selection_foreground)
c0=$(get color0)
c1=$(get color1)
c2=$(get color2)
c3=$(get color3)
c4=$(get color4)
c5=$(get color5)
c6=$(get color6)
c7=$(get color7)
c8=$(get color8)
c9=$(get color9)
c10=$(get color10)
c11=$(get color11)
c12=$(get color12)
c13=$(get color13)
c14=$(get color14)
c15=$(get color15)

# sanity: background must have parsed, else the toml format is off
[ -n "$bg" ] || {
  echo "failed to parse $TOML (no background)" >&2
  exit 1
}

# ---- render each app's color file --------------------------------------
# foot: terminal palette maps 1:1 (no #). bright = the 8-15 set.
cat >"$HOME/.config/foot/colors.ini" <<EOF
# generated by theme-pick.sh from theme: $THEME
[colors-dark]
background=$bg
foreground=$fg
regular0=$c0
regular1=$c1
regular2=$c2
regular3=$c3
regular4=$c4
regular5=$c5
regular6=$c6
regular7=$c7
bright0=$c8
bright1=$c9
bright2=$c10
bright3=$c11
bright4=$c12
bright5=$c13
bright6=$c14
bright7=$c15
EOF

# ---- swayosd: render custom standalone style.css -----------------------
mkdir -p "$HOME/.config/swayosd"
cat >"$HOME/.config/swayosd/style.css" <<EOF
/* generated by theme-pick.sh from theme: $THEME */
@define-color border-color      #$accent;
@define-color background-color  #$bg;
@define-color label             #$fg;
@define-color image             #$fg;
@define-color progress          #$accent;

window {
  border-radius: 0;
  opacity: 0.97;
  border: 2px solid @border-color;
  background-color: @background-color;
}

label {
  font-family: 'JetBrainsMono Nerd Font';
  font-size: 11pt;
  color: @label;
}

image {
  color: @image;
}

progressbar {
  border-radius: 0;
}

progress {
  background-color: @progress;
}
EOF

# waybar: @define-color names match your existing style.css usage (with #).
cat >"$HOME/.config/waybar/colors.css" <<EOF
/* generated by theme-pick.sh from theme: $THEME */
@define-color background  #$bg;
@define-color surface     #$c0;
@define-color surface_alt #$c8;
@define-color foreground  #$fg;
@define-color primary     #$accent;
@define-color on_primary  #$bg;
@define-color secondary   #$c4;
@define-color accent      #$c5;
@define-color urgent      #$c1;
@define-color muted       #$c7;
EOF

# mako: this mako version has no 'include' support, so render the full config
# from the template, substituting colors. Preserves all non-color mako settings.
sed -e "s|__BG__|#${c0}f0|g" \
  -e "s|__FG__|#$fg|g" \
  -e "s|__BORDER__|#$accent|g" \
  -e "s|__URGENT__|#$c1|g" \
  "$HOME/.config/mako/mako-config.template" >"$HOME/.config/mako/config"

# ---- cava: regenerate config with themed gradient (preserves settings) ----
# cava live-reloads on config change, so an open cava recolors instantly.
if [ -f "$HOME/.config/cava/cava.template" ]; then
  sed -e "s|__G1__|#${c8}|g" \
    -e "s|__G2__|#${c4}|g" \
    -e "s|__G3__|#${c4}|g" \
    -e "s|__G4__|#${accent}|g" \
    -e "s|__G5__|#${accent}|g" \
    -e "s|__G6__|#${c5}|g" \
    -e "s|__G7__|#${c5}|g" \
    -e "s|__G8__|#${fg}|g" \
    "$HOME/.config/cava/cava.template" >"$HOME/.config/cava/config"
fi

# ---- yazi: generate flavor from palette, point theme.toml at it ----
if [ -d "$HOME/.config/yazi" ]; then
  mkdir -p "$HOME/.config/yazi/flavors/mango.yazi"
  cat >"$HOME/.config/yazi/flavors/mango.yazi/flavor.toml" <<YAZ
# generated by theme-pick.sh from theme: $THEME
[mgr]
cwd = { fg = "#$accent" }
hovered = { fg = "#$bg", bg = "#$accent" }
preview_hovered = { underline = true }
find_keyword = { fg = "#$c3", italic = true }
marker_selected = { fg = "#$c2", bg = "#$c2" }
[mode]
normal_main = { fg = "#$bg", bg = "#$accent", bold = true }
select_main = { fg = "#$bg", bg = "#$c2", bold = true }
[status]
separator_open = ""
separator_close = ""
YAZ
  cat >"$HOME/.config/yazi/theme.toml" <<'YTH'
[flavor]
dark  = "mango"
light = "mango"
YTH
fi

# ---- gtk: dark + adw-gtk3-dark + papirus, live via gsettings ----
if command -v gsettings >/dev/null 2>&1; then
  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null || true
  gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark' 2>/dev/null || true
fi

# ---- swaylock: render lock config from template (themed ring) ----
if [ -f "$HOME/.config/swaylock/swaylock.template" ]; then
  sed -e "s|__BG__|${bg}|g" \
    -e "s|__FG__|${fg}|g" \
    -e "s|__SURFACE__|${c0}|g" \
    -e "s|__ACCENT__|${accent}|g" \
    -e "s|__PRIMARY__|${accent}|g" \
    -e "s|__URGENT__|${c1}|g" \
    "$HOME/.config/swaylock/swaylock.template" >"$HOME/.config/swaylock/config"
fi

# rofi: .rasi color vars. LOAD-BEARING -- imported by kev.rasi (launcher) and
# dmenu.rasi (clipboard/emoji pickers). Do not remove.
cat >"$HOME/.config/rofi/colors.rasi" <<EOF
/* generated by theme-pick.sh from theme: $THEME */
* {
    background:     #$bg;
    background-alt: #$c0;
    foreground:     #$fg;
    selected:       #$accent;
    on-selected:    #$bg;
    accent:         #$c5;
    urgent:         #$c1;
    muted:          #$c7;
}
EOF

# mango: 0xRRGGBBAA. accent = focus border, c8 (dark gray) = unfocused.
cat >"$HOME/.config/mango/theme.conf" <<EOF
# generated by theme-pick.sh from theme: $THEME
focuscolor=0x${accent}FF
bordercolor=0x${c8}FF
urgentcolor=0x${c1}FF
dropcolor=0x${c5}55
splitcolor=0x${c4}FF
EOF

# ---- extras: btop / nvim / icons -----------------------------------------
# Each guarded so a missing tool/file/theme is a silent skip, never an abort.

# btop: btop.conf points at theme 'current', so overwrite that file.
if [ -f "$THEMES_DIR/$THEME/btop.theme" ]; then
  mkdir -p "$HOME/.config/btop/themes"
  cp "$THEMES_DIR/$THEME/btop.theme" "$HOME/.config/btop/themes/current.theme"
fi

# nvim (LazyVim): drop the theme's plugin spec in as plugins/theme.lua.
# Note: won't hot-reload a running nvim; takes effect next launch, and lazy may
# pause once to install the colorscheme plugin if it's new.
if [ -f "$THEMES_DIR/$THEME/neovim.lua" ] && [ -d "$HOME/.config/nvim/lua/plugins" ]; then
  cp "$THEMES_DIR/$THEME/neovim.lua" "$HOME/.config/nvim/lua/plugins/theme.lua"
fi

# icons: recolor Papirus-Dark folders to a hand-picked color per theme.
# Papirus-Dark must be user-owned (~/.local/share/icons) so no sudo needed.
if command -v papirus-folders >/dev/null 2>&1; then
  case "$THEME" in
  nord) pcol=nordic ;;
  gruvbox) pcol=brown ;;
  catppuccin) pcol=violet ;;
  catppuccin-latte) pcol=violet ;;
  tokyo-night) pcol=blue ;;
  rose-pine) pcol=pink ;;
  everforest) pcol=green ;;
  kanagawa) pcol=indigo ;;
  ristretto) pcol=deeporange ;;
  osaka-jade) pcol=teal ;;
  matte-black) pcol=grey ;;
  vantablack) pcol=grey ;;
  white) pcol=white ;;
  solitude) pcol=bluegrey ;;
  miasma) pcol=brown ;;
  lumon) pcol=cyan ;;
  hackerman) pcol=green ;;
  flexoki-light) pcol=orange ;;
  ethereal) pcol=violet ;;
  last-horizon) pcol=orange ;;
  retro-82) pcol=yellow ;;
  *) pcol=blue ;; # fallback for any unmapped theme
  esac
  papirus-folders -C "$pcol" -t Papirus-Dark >/dev/null 2>&1 &
fi

# wallpaper: intentionally NOT handled here. The themes' bundled backgrounds are
# generic; curate your own in ~/Pictures/Wallpapers and use wallpaper.sh instead.

# ---- reload everything (same hooks matugen used) -----------------------
pkill -SIGUSR2 waybar 2>/dev/null || true
makoctl reload 2>/dev/null || true
mmsg dispatch reload_config >/dev/null 2>&1 || true

# swayosd: restart the systemd user service so it picks up the new style.css.
# Requires ~/.config/systemd/user/swayosd.service (Restart=always) to exist and
# be started once at login (exec-once=systemctl --user start swayosd.service).
# No manual pkill/nohup fallback: hand-launching from this shell left the server
# tied to the terminal session, which is why it died after a theme reload.
systemctl --user restart swayosd.service 2>/dev/null || true

printf '%s\n' "$THEME" >"$STATE"
echo "applied theme: $THEME"
